server:
  port: 90
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/alissl?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 3
      maximum-pool-size: 20
      max-lifetime: 30000
      connection-test-query: select 1
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
jwt:
  expires-hour: 6
  exclude-path-patterns: /,/index.html,/assets/**,/login
login:
  username: "admin"
  password: "admin"
ali:
  accessKeyId: "accessKeyId"
  accessKeySecret: "accessKeySecret"
  username: "任总" #申请证书联系人姓名
  phone: "123456**" #申请证书联系人电话
  email: "123**@163.com" #申请证书联系人邮箱
  companyName: "**科技有限公司" #申请证书公司名称